name: CI
on:
  push:
  
  pull_request:

env:
  R2PM_GITSKIP: 1
  R2PM_GITDIR: ${{ github.workspace }}/radare2-extras

jobs:
  build-extras:
    name: Build radare2 extras
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      id: vcs_radare
      with:
        repository: radareorg/radare2
        ref: master
        path: ./radare2
    - name: Install dependencies
      run: |
        sudo apt-get --assume-yes update
        sudo apt-get --assume-yes install libjansson-dev libboost-dev libcurl4-openssl-dev python3-wheel python3-setuptools && sudo pip3 install meson ninja
    - name: Load cache
      id: cache
      uses: actions/cache@v4
      with:
        path: ./radare2/build
        key: ${{ runner.os }}-${{ hashFiles('**', '!**/.github/**', '!**/.git/**') }}
    - name: Build radare2
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        echo "/usr/local/bin" >> $GITHUB_PATH
        meson --prefix=/usr --buildtype=release build && ninja -C build 
      working-directory: ./radare2
    - name: Install radare2
      run: |
        sudo ninja -C build install
      working-directory: ./radare2
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        path: ${{ env.R2PM_GITDIR }}
    - name: Init r2pm
      run: r2pm -U
    - name: Compile and install plugins
      run: |
        set -e 
        for folder in "${R2PM_GITDIR}"/*/; do
            if [ -n $folder/Makefile ]; then
                p=${folder%/}
                echo "$p"
                r2pm -i "$p"
            fi
        done
        set +e
      working-directory: ${{ env.R2PM_GITDIR }}
    - name: Test plugins
      working-directory: radare2/test
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        set -e
        make all
        set +e

